services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/dom/data/wordpress:/var/www/htrml
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    volumes:
      - /home/dom/data/mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - /home/dom/data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge